name: grimreach_server
description: Dart backend server framework
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  grimreach_api:
    path: ../grimreach_api

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
